path_classifiers:
  docs:
    - exclude: / # ignore default classification
    - docs
  library:
    - exclude: / # ignore default classification
    - pybind11
    - external_libraries
  test:
    - exclude: / # ignore default classification
    - tests

extraction:
  cpp:
    after_prepare:
      - mkdir custom_cmake
      - wget --quiet -O - "http://www.cmake.org/files/v3.17/cmake-3.17.5-Linux-x86_64.tar.gz" | tar --strip-components=1 -xz -C custom_cmake
      - export PATH=$(pwd)/custom_cmake/bin:${PATH}
    index:
      build_command:
      - cmake --version
      - cmake -S python -B build
      - cmake --build build
