name: Test C++

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  test_cpp:
    name: build (${{ matrix.os }}, C++)
    
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      max-parallel: 4

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: "**/cpm_modules"
          key: ${{ github.workflow }}-cpm-modules-${{ hashFiles('**/CMakeLists.txt', '**/*.cmake') }}

      - name: Configure
        run: cmake -Stest -Bbuild

      - name: Build
        run: cmake --build build --config Debug -j4

      - name: Test
        run: |
          cd build
          ctest --build-config Debug