name: Test Python

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test_python:
    name: build (${{ matrix.os }}, ${{ matrix.python-version }})
    
    runs-on: ${{ matrix.os }}

    strategy:
      max-parallel: 4
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        python-version: [3.8]
        include:
          - python-version: 3.6
            os: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install package
      run: |
        pip install .

    - name: Test with pytest
      run: |
        pip install pytest
        pytest
